# Site settings
title: Ruchi Bommaraju
description: Ruchi Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ruchi Bommaraju
user_description: Hello! I am a student from India with good communication skills who passionately learns and seeks corporate experience looking for an internship position to utilise my knowledge and transform my skills into competent goals. I aspire to gain experience in coding to became a leading programmer in the industry.
user_title: Intern
email: Ruchidattab@gmail.com
# twitter_username: lorem_ipsum
instagram_username: imruchiii
linkedin_username: Ruchi Bommaraju
github_username:  imruchi
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
